# Generated by Django 5.0.6 on 2024-06-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_shippingaddress_delete_shippingadddate_added'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='my_customer_table',
        ),
        migrations.AlterModelTable(
            name='order',
            table='OrderDJ',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='OderItem',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
        migrations.AlterModelTable(
            name='shippingaddress',
            table='ShippingAddress',
        ),
    ]
