# Generated by Django 5.0.6 on 2024-06-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_customer_table_alter_order_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
